### PR TITLE
Update to penguin app icons, and start requesting user_events permission.

### PR DESCRIPTION
**Pull request by mikelambert**

### CODE REVIEW

**Comment by mikelambert** [comment]
Let me know if you want to keep your branch as the master (in which case I can keep pushing to you, and you can gatekeep any changes I make, and releases come building off your tree).

Or if you want to use the dancedeets/ version at https://github.com/DanceDeets/dancedeets-ios as authoritative, in which case you and i both push to that (and presumably whoever would need to pull/sync from it before pushing code live to get both of our stuff).

**Comment by mikelambert** [comment]
This now adds the user_events permission. Not sure how to do this separately, I guess I'd need to create and push up a new branch with just my single one-line change?

**Comment by DaveX101** [comment]
Sounds fine to me to use dancedeets as authoritative. Are you going to try to make an app store version yourself this time? I can PR into dancedeets/ now for things. Let me know if you have any trouble updating a version, I had done it successfully from the official account last time.

**Comment by DaveX101** [comment]
:ship:

**Pull request closed without merging**
